PersonalWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('', include('Portfolio.urls')),
    path('admin/', admin.site.urls),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Portfolio/urls.py
from django.urls import path
from . import views

app_name = "portfolio"

urlpatterns = [

    path('', views.home, name='home'),
    path('index', views.home, name='index'),
    path('certificate/<int:id>', views.certificate, name='certificate'),
    path('education/<int:id>', views.education, name='education'),
    path('project/<int:id>', views.project, name='project'),
    path('download/', views.download_file, name='download_file'),


]

Portfolio/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class About(models.Model):
    desc = models.TextField()
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    zipcode = models.IntegerField()
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=100)
    img = models.ImageField(upload_to='pics')
    def __str__(self):
        return self.name

class Education(models.Model):
    date=models.CharField(max_length=100)
    degree =models.CharField(max_length=100)
    university=models.CharField(max_length=100)
    desc=models.TextField()

    def __str__(self):
        return self.degree

class Experience(models.Model):
    date = models.CharField(max_length=100)
    framework = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    desc = models.TextField(max_length=100)
    def __str__(self):
        return self.framework


class SkillCategory(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Skill(models.Model):
    category = models.ForeignKey(SkillCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name



class Certification(models.Model):
    name = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='pics')  # Make sure to configure your MEDIA_ROOT and MEDIA_URL settings

    def __str__(self):
        return self.name

class Project(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    project_scope = models.CharField(max_length=200)
    start_date =models.CharField(max_length=200)
    def __str__(self):
        return self.title

class Message(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    subject = models.CharField(max_length=200)
    information = models.TextField()

    def __str__(self):
        return self.name

Portfolio/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import *
from django.conf import settings
from django.core.mail import send_mail
import os


# Create your views here.

def home(request):
    abouts = About.objects.all()
    eduations = Education.objects.all().order_by('id')
    experiences = Experience.objects.all().order_by('id')
    categories = SkillCategory.objects.all()
    certifications= Certification.objects.all()
    projects = Project.objects.all()
    if request.method == "POST":
        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        information = request.POST['information']
        someth = Message(name=name, email=email, subject=subject, information=information)
        someth.save()
        send_mail(name,
                  'Thankyou for your message',
                  'pradipchapagain123@gmail.com',
                  [email])
    return render(request, 'index.html', {'abouts': abouts,'eduations':eduations,'experiences' : experiences,'categories': categories,'certifications': certifications,'projects' :projects})


def education(request,id):
    eduations = Education.objects.get(pk=id)
    return render(request, 'education.html', {'eduations': eduations})

def project(request, id):
    project = Project.objects.get(pk=id)
    return render(request, 'projects.html', {'project': project})

def index(request):
    abouts = About.objects.all()
    eduations = Education.objects.all().order_by('id')
    experiences = Experience.objects.all().order_by('id')
    categories = SkillCategory.objects.all()
    certifications = Certification.objects.all()
    projects = Project.objects.all()
    return render(request, 'index.html',
                  {'abouts': abouts, 'eduations': eduations, 'experiences': experiences, 'categories': categories,
                   'certifications': certifications, 'projects': projects})


def certificate(request, id ):
    certificate = Certification.objects.get(pk=id)
    return render(request, 'certificate.html', {'certificate': certificate})


def download_file(request):
    file_path = os.path.join(settings.MEDIA_ROOT, 'pics', 'work.png')  # Provide the correct path to your file
    if os.path.exists(file_path):
        with open(file_path, 'rb') as file:
            response = HttpResponse(file.read(), content_type='application/octet-stream')
            response['Content-Disposition'] = f'attachment; filename="{os.path.basename(file_path)}"'
            return response
    else:
        return HttpResponse("File not found", status=404)



def footer_data(request):
    abouts = About.objects.all()
    return render(request,'test.html',{ 'abouts': abouts})

templates/aaaa.html
{% extends "test.html" %}


{% block header %}

<h1> Pradip Chapagain </h1>

{% endblock %}


{% block content %}
    <p style="color: black ;" >This is the content of the child template.</p>
{% endblock %}

templates/certificate.html
{% extends "test.html" %}


{% block header %}

<div class="project img ftco-animate d-flex justify-content-center align-items-center" style=" background-image:url({{ certificate.image.url }}) ; ">
</div>
{% endblock %}


{% block content %}


<div class="text pl-3">
     <h2>Course Title: {{ certificate.name }}</h2>
    <span class="position" style="color: black ;">{{ certificate.description  }}</span>

 </div>


{% endblock %}

templates/education.html
{% extends "test.html" %}


{% block header %}

<h2> {{ eduations.degree }} </h2>

{% endblock %}


{% block content %}
    <p style="color: black ;" >This is the content of the child template.</p>
{% endblock %}

templates/projects.html
{% extends "test.html" %}


{% block header %}

<h1> {{ project.title }} </h1>

{% endblock %}


{% block content %}
 <div class="text pl-3">
     <span class="date">Date : {{ project.start_date }}</span>
     <h2>Title:{{ project.title }}</h2>
     <span class="position">{{ project.scope }}</span>
     <span class="position" style="color: black ;"> {{ project.description }}</span>
 </div>

{% endblock %}

templates/test.html
<!DOCTYPE html>
{% load static %}
{% static "images" as baseUrl%}

<html lang="en">
  <head>
    <title>Pradip Chapagain </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">
	  <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
	  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha384-KyZXEAg3QhqLMpG8r+3doRWGveEc2YYUanhRdFxlj2UbbV+8dWNI5l2n6Xm6j2f5" crossorigin="anonymous">
<style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        header {
            background-color: #333;
            color: white;
            text-align: center;
            padding: 1rem;
        }

        .skills {
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 2rem;
        }

        table {
            border-collapse: collapse;
            width: 100%;
            max-width: 800px;
            margin: 0 auto;
            border: 1px solid #ddd;
        }

        th, td {
            border: 1px solid #000DDD;
            padding: 8px;
            text-align: left;
            font-weight:bold;
            color:#000000

        }

        th {
            background-color: #add8e6;
        }
    </style>


  </head>
  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">


    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar ftco-navbar-light site-navbar-target" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="{% url 'portfolio:index' %}"><span>P</span> radip Chapagain </a>
	      <button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav nav ml-auto">
	          <li class="nav-item"><a href="{% url 'portfolio:index' %}" class="nav-link"><span>Home</span></a></li>
	        </ul>
	      </div>
	    </div>
	  </nav>
	  <section class="hero-wrap js-fullheight">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight justify-content-center align-items-center">
          <div class="col-lg-8 col-md-6 ftco-animate d-flex align-items-center">
          	<div class="text text-center">

                 {% block header %}Default Header{% endblock %}

                <!--  Content goes here     -->
            </div>
            </div>
          </div>
        </div>
      </div>

    </section>
      <div class="mouse">
				<a href="#" class="mouse-icon">
					<div class="mouse-wheel"><span class="ion-ios-arrow-round-down"></span></div>
				</a>
			</div>


    <!-- Description Comes Here -->

{% block content %}


    {% endblock %}



    <footer class="ftco-footer ftco-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">30/ 73 Mani road Clearmont</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">0404318945</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">pradipchapagain981@gmail.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p>Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This is Developed <i class="icon-heart color-danger" aria-hidden="true"></i> by Pradip Chapagain</p>
          </div>
        </div>
      </div>
    </footer>



  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>
  <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'js/scrollax.min.js' %}"></script>

  <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>